### ISSUE TITLE
Binary build

### ISSUE THREAD

**Issue by elizhenin** [Noxime/nihongo#1]
Hello. May you publish binary release, or instruction how to do this byself?
I'm know nothing about Rust, and have tried to install it and build on ubuntu 18.04. Something goes wrong, it tells me that "feachure" is not supported, but supported in nightly version of Rust. I've no idea how to correctly install it and compile your sources

**Comment by 64** [comment]
From the project root folder, do:
```
rustup install nightly
rustup override set nightly
cargo run
```

**Comment by elizhenin** [comment]
Still not build, showing the folowing:


  Compiling nihongo v0.0.0 (/home/user/Downloads/nihongo-master)
error[E0557]: feature has been removed
 --> src/main.rs:2:12
  |
2 | #![feature(const_fn)]
  |            ^^^^^^^^ feature has been removed
  |
  = note: split into finer-grained feature gates

warning: unused import: `sdl2::Sdl`
 --> src/display.rs:3:5
  |
3 | use sdl2::Sdl;
  |     ^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: use of deprecated function `std::thread::sleep_ms`: replaced by `std::thread::sleep`
   --> src/main.rs:263:17
    |
263 |         thread::sleep_ms(2);
    |                 ^^^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

error[E0599]: no method named `get_extended_function_info` found for struct `CpuId` in the current scope
   --> src/main.rs:116:28
    |
116 |             let brand = id.get_extended_function_info()
    |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `get_extended_feature_info`

Some errors have detailed explanations: E0557, E0599.
For more information about an error, try `rustc --explain E0557`.
warning: `nihongo` (bin "nihongo") generated 2 warnings
error: could not compile `nihongo` due to 2 previous errors; 2 warnings emitted
